---
name: Validate Dockerfile
# From: https://github.com/luke142367/Docker-Lint-Action

on:
  pull_request:
    paths:
      - '**/Dockerfile'
jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: luke142367/Docker-Lint-Action@v1.0.0
        with:
          target: Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile
